### ISSUE TITLE
Setup ledger-js build

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/ledger#13]
- [x] Runs build
- [ ] Runs tests
- [x] Deploys to NPM

**Comment by realrhys** [comment]
As discussed, the tests are not unit tests. I do not run them.

Note also, that I would like to change the NPM_TOKEN. Currently it is mine, however, I would prefer if were able to change it to someone elses or a volentixlabs account.

Finally, changing the repo name is easy. Simply change the name in package.json and away we go.

Finally, finally, DO NOT change the "version": "VERSION", line as it used to update the build numbers.
