### ISSUE TITLE
Setup ledger build

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/ledger#14]
- [ ] Runs build
- [ ] Deploys EOS contract

**Comment by realrhys** [comment]
The URL for connecting to the jungle testnet is:
http://dev.cryptolions.io:38888/v1/chain/get_info

A production url is:
 http://node2.liquideos.com:8888/v1/chain/get_info

**Comment by shawnlauzon** [comment]
So Circle CI will deploy the contract to the jungle testnet?
